language: python
python:
    - "3.7"
install:
    - pip install tox coveralls
script:
  - tox
after_success: coveralls
branches:
  only:
    - master
addons:
  apt:
    packages:
      - language-pack-es
